### ISSUE TITLE
Grafana "Ruby On Rails Performance (per Request)" does not work from provided link

### ISSUE THREAD

**Issue by rikikonikoff** [InfluxCommunity/influxdb-rails#106]
I'm in the process of setting up influxdb and grafana for my rails app, and I noticed something quite strange when I tried to import this dashboard that you [link to from your sample-dashboard README](https://github.com/influxdata/influxdb-rails/tree/master/sample-dashboard#installation).

I copied the dashboard id from your "Request Dashboard" link and imported it to my grafana account. It claimed to import the dashboard successfully, but then instead of redirecting me to a normal dashboard I see this:
<img width="1276" alt="Screenshot 2020-04-24 12 32 01" src="https://user-images.githubusercontent.com/23462196/80237993-a3eaa100-862b-11ea-8bb7-635607dbba3b.png">

I see the same when I navigate elsewhere on the site and then attempt to revisit this particular dashboard.

I'm not sure if this is an issue with your link or with the grafana template or something else, but I thought you might want to know some of your instructions are not working. Thanks!

**Comment by hennevogel** [comment]
hey @rikikonikoff what grafana version are you using?

**Comment by rikikonikoff** [comment]
@hennevogel 5.2.4

**Comment by hennevogel** [comment]
I'll test it with that version, might be that this only works with something more recent.

I just successfully imported with 6.7.3

**Comment by ChrisBr** [comment]
@rikikonikoff can you confirm that it works for you with a later Grafana version too?

**Comment by rikikonikoff** [comment]
I still get the same error - sorry!

**Comment by ChrisBr** [comment]
@rikikonikoff still 5.2.4 or have you tried with a newer version?

**Comment by hennevogel** [comment]
I just imported both dashboard into a 5.2.4 instance without a problem. So this must be something with your grafana, nothing we can do about this. Sorry....

**Comment by hennevogel** [comment]
Here is how:

1. run grafana on http://0.0.0.0:4000
    `docker run -d -p 4000:3000 grafana/grafana:5.2.4`
1. login as `admin` with the password `admin`
1. create a "fake" influxdb data source on http://0.0.0.0:4000/datasources
1. import the dashboard via http://0.0.0.0:4000/dashboard/import

**Comment by rikikonikoff** [comment]
Ok, thanks for looking into it

**Comment by hennevogel** [comment]
sorry we can't be of assistance :disappointed: 

would be cool if you let us know when you find a solution @rikikonikoff
