### ISSUE TITLE
[RFC] Implement plugin system

### ISSUE THREAD

**Issue by ChrisBr** [InfluxCommunity/influxdb-rails#107]
Currently we only implement a selection of ActiveSupport instrumentation events but there are several more which might be interesting as well as some apps implement custom events.

We should a possibility to instrument any Active Support instrumentation event.

Proposal for a configuration syntax which is a hash and each key, value pair consists of the event name and a proc which returns a hash with tags and values.

```ruby
InfluxDB::Rails.configure do |config|
  config.custom_instrumentations = {
    "request.faraday" => proc do |data|
      url = data[:url]
      http_method = env[:method].to_s.upcase
      {
        tags:   { host: url.host, http_method: http_method },
        values: { uri: url.request_uri }
      }
    end
  }
end
```

https://github.com/lostisland/faraday/blob/a285d7a8b6f5f3cfb1d273aef2ed1ac007ef8b1d/docs/middleware/request/instrumentation.md

**Comment by hennevogel** [comment]
I guess nothing stops you from subscribing to events and use block instrumentation now right?

**Comment by ChrisBr** [comment]
Yeah makes sense!
