### ISSUE TITLE
Disable influxdb-rails' main Feature: Logging

### ISSUE THREAD

**Issue by PascalTurbo** [InfluxCommunity/influxdb-rails#12]
Hi,

this Feature-Request may sound crazy to you but I'm misusing influxdb-rails for an other task: accessing influxdb from an rails application.

Sure, it would be no problem using influxdb-ruby but influxdb-rails brings the application-wide accessible InfluxDB::Client and an comfortable initializer / configuration.

Maybe it would be easy to offer a configuration for disabling the logging feature.

Viele Grüße
Pacsal

**Comment by KevinBongart** [comment]
I'd love to see that as well

**Comment by nickjacob** [comment]
you can get pretty close with:

(in initializers/influxdb-rails.rb)

``` ruby
InfluxDB::Rails.configure do |config|

  # ...

  config.logger = Logger.new(STDERR)
  config.logger.level = Logger::FATAL

end
```

**Comment by thom-nic** [comment]
I was looking for (I think?) the same thing as OP.  I don't care about rails controller or DB query metrics, but I _do_ want to push my own timeseries data to influx from my rails app. So will changing the `config.logger` disable those rails metrics?

**Comment by thom-nic** [comment]
**Update**: While @nickjacob's suggestion will disable rails logging from influxdb-rails code it I'm pretty sure changing the logger level won't prevent app metrics (e.g. controller runtimes, render exceptions, etc.) from being pushed to InfluxDB.  I believe @PascalTurbo was asking how to disable **metrics collection**, not logging in the `Rails.logger` sense. 

After browsing the codebase I think these two configuration options should disable the majority if not all app metrics collection:

``` ruby
  config.ignored_environments << Rails.env
  config.instrumentation_enabled = false
```

**Comment by anthonator** [comment]
I'm also interested in this. I proposed an application wide config to [influxdata/influxdb-ruby](https://github.com/influxdata/influxdb-ruby) but [they weren't interested](https://github.com/influxdata/influxdb-ruby/issues/143).

**Comment by thom-nic** [comment]
No I agree that approach is generally a bad idea and in this particular case I don't think it's necessary at all.  influx-rails is managing a singleton that you can configure as documented.  The only piece missing was what I provided in [my comment above](https://github.com/influxdata/influxdb-rails/issues/12#issuecomment-209441132).  I can call `InfluxDB::Rails.client.write_point` all day long to write data to Influx without this gem automatically logging app metrics.

**Comment by dmke** [comment]
What @thom-nic wrote is correct:

> After browsing the codebase I think these two configuration options should
> disable the majority if not all app metrics collection:
>
> ```ruby
>  config.ignored_environments << Rails.env
>  config.instrumentation_enabled = false
> ```

Simply put this in your initializer and influxdb-rails won't submit performance metrics.

**Comment by thom-nic** [comment]
I also added this:
```
Rails.application.config.middleware.delete InfluxDB::Rails::Rack
```
that middleware is used for collecting metrics, no need for it in the request pipeline if you're just using the library to manage an influxdb connection instance.

**Comment by dmke** [comment]
The middleware only reports exceptions, but yeah: no need to pass the request through that.
