### ISSUE TITLE
InfluxDB: Cannot write data

### ISSUE THREAD

**Issue by jmarbach** [InfluxCommunity/influxdb-rails#153]
Hi,

I am trying to connect my rails app to my InfluxDB that I set up with Aiven.

When I run `rails server` with my InfluxDB config, I get the following errors in my logs in development and production:

```
E, [2021-01-06T17:28:00.000942 #65017] ERROR -- InfluxDB: Cannot write data: #<InfluxDB::ConnectionError: The server has sent incomplete data (insufficient resources are a possible cause).>
```

My config:

```
  config.client.database = "defaultdb"
  config.client.hosts = ["xxxxxxxxxx.aivencloud.com"]
  config.client.port = 15457

  ## If you've setup user authentication (and activated it in the server
  ## config), you need to configure the credentials here.
  config.client.username = "user"
  config.client.password = "password"
```

Any ideas on how I can resolve this config issue?

**Comment by hennevogel** [comment]
This points¹ to `EOFError`, the server does not answer or only answers garbage. Or `Zlib::Error`, the server sends incorrectly compressed answer. You should check both.

Does sending data with curl or any other low level network tool work?

¹ https://github.com/influxdata/influxdb-ruby/blob/b708621c891b2b6c486fff75528e1a143ac576cd/lib/influxdb/errors.rb#L32-L38

**Comment by chornsby** [comment]
The InfluxDB services on Aiven all run with [HTTPS enabled](https://docs.influxdata.com/influxdb/v1.8/administration/https_setup/) so you'll need to add `use_ssl = true` to the configuration.

```patch
   config.client.database = "defaultdb"
   config.client.hosts = ["xxxxxxxxxx.aivencloud.com"]
   config.client.port = 15457
+  config.client.use_ssl = true

   ## If you've setup user authentication (and activated it in the server
   ## config), you need to configure the credentials here.
   config.client.username = "user"
   config.client.password = "password"
```

Since enabling HTTPS is strongly recommended in the InfluxDB documentation perhaps we could make the option more easily discoverable by adding it to the [initial configuration scaffold](https://github.com/influxdata/influxdb-rails/blob/master/lib/rails/generators/influxdb/templates/initializer.rb)?

**Comment by ChrisBr** [comment]
@chornsby brilliant idea 👍  If you're keen, please send a PR and I will be happy to merge.

**Comment by chornsby** [comment]
Sure thing, very keen! :smile:

**Comment by ChrisBr** [comment]
Fixed in https://github.com/influxdata/influxdb-rails/pull/154

**Comment by ChrisBr** [comment]
Thanks everyone 👏

**Comment by kinsomicrote** [comment]
Hello, I am faced with same issue, here is what my config looks like;

```
config.client.database = "db"
 config.client.hosts = ["host"]
  config.client.port = 8086
  config.client.use_ssl = true

  ## If you've setup user authentication (and activated it in the server
  ## config), you need to configure the credentials here.
  config.client.username = "xxxx"
  config.client.password = "xxx"
```

I'm able to send a request to influxdb from another container in the same network, and also from my machine using postman. I can see the requests in the container logs for influxdb. But my Rails app keeps giving the same error, locally and on my server. Any hints?
