### ISSUE TITLE
'invalid number' error when loading Rails page using influx-20 branch

### ISSUE THREAD

**Issue by macmartine** [InfluxCommunity/influxdb-rails#173]
I'm using the influxdb-20 branch. It connects fine and send a little data, but then throws this guy:

`InfluxDB2::InfluxError: unable to parse 'rails,format=html,hook=process_action,http_method=GET,location=DashboardController#show,method=DashboardController#show,server=pop-os,status=200 controller=2549i,db=1838i,request_id="5ab55ec7-000a-4d78-a4c5-22fb0035c1a8",started=2021-07-01 22:54:29 UTC,view=47i 1625180071846983424': invalid number`

Anything obvious that stands out here, or is this a bug in the gem?

**Comment by ChrisBr** [comment]
Thanks @macmartine. I will have a look at this tomorrow, very odd but seems related to the new client.

**Comment by macmartine** [comment]
@ChrisBr I narrowed it down to the 'started' variable in the following payload... Here's the end of the payload that's causing the error:

`'rails,format=html,hook=process_action,http_method=GET,location=Setup::AdvocatesController#index,method=Setup::AdvocatesController#index,server=pop-os,status=200 controller=386i,db=59i,request_id="4acb8c77-f05d-4bc9-99af-23a333a83772",started=2021-07-01 23:55:49 UTC,view=19i 1625183749598635008'`

If the 'started' variable is removed, all is well.

UPDATE:
Had to add this back, but change 'time_precision' to just 'precision':
https://github.com/influxdata/influxdb-rails/blob/860a6d41e789de052a61f39a1ce1ccf69102b75a/lib/influxdb/rails/middleware/request_subscriber.rb#L35

But still get: 'undefined method `convert_timestamp' for InfluxDB:Module' .... can't find where that method is/was.

Also had to remove the InfluxDB:: namespace from:
https://github.com/influxdata/influxdb-rails/blob/60edb695e4e98ce23a192122a472c99268ec28da/lib/influxdb/rails/middleware/subscriber.rb#L33

**Comment by ChrisBr** [comment]
@macmartine can you check what type `start.utc` is because if it's a `Time` object it should get automatically escaped now.

https://github.com/influxdata/influxdb-client-ruby/blob/3c5ba14273b5b65c53f608eb00827eeb65aceb42/lib/influxdb2/client/point.rb#L195-L217

> But still get: 'undefined method `convert_timestamp' for InfluxDB:Module' .... can't find where that method is/was.

> Also had to remove the InfluxDB:: namespace from:

`convert_timestamp` was a method from influxdb-ruby (1.0). In influxdb-client-ruby (2.0) we don't need / have this method anymore and it should get implicitly converted.

**Comment by ChrisBr** [comment]
Also which Rails version are you using?

**Comment by ChrisBr** [comment]
Any update @macmartine ?

**Comment by macmartine** [comment]
@ChrisBr Sorry, I was just experimenting with this and not using it anymore at the moment.
Rails version: 5.2.4.5

Thanks!

**Comment by hennevogel** [comment]
`started=2021-07-01 23:55:49 UTC` looks weird, this should be EPOCH instead.  Are we missing an `.to_i` somewhere? 

https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#timestamp

**Comment by ChrisBr** [comment]
@hennevogel as mentioned, this should be handled by the new client as long as this is a time object.

https://github.com/influxdata/influxdb-client-ruby/blob/3c5ba14273b5b65c53f608eb00827eeb65aceb42/lib/influxdb2/client/point.rb#L195-L217

My suspicion is that this is a String. But as it's coming from Rails it should be a time object.

**Comment by rubhanazeem** [comment]
> `started=2021-07-01 23:55:49 UTC` looks weird, this should be EPOCH instead. Are we missing an `.to_i` somewhere?
> 
> https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#timestamp

This should be handled by the client. The client is responsible for converting all the timestamps to integers. Client is not checking the presence of timestamps in tags and fields and just converting it to a string instead of an int. I've opened a PR in client to address this issue https://github.com/influxdata/influxdb-client-ruby/pull/131

**Comment by hennevogel** [comment]
Fixed upstream, thanks @rubhanazeem 💐
