### ISSUE TITLE
"Errors" in Requests per … Panel

### ISSUE THREAD

**Issue by michaelbaisch** [InfluxCommunity/influxdb-rails#188]
Hello everyone,

I was noticing red bars in the `Requests per…` Panel in the `Ruby on Rails Performance` dashboard. Digging into it it seems that only rows with `status = 200` are considered "success" and everything else is an "error". I have a few requests where `status` is `null` (which actually should be `302`) and some `302`.

I would suggest counting `302` status requests also as "success", since often it's not something going wrong and to worry about. Especially when using Active Storage where resources are served with redirects.

What are your thoughts?

Greetings,
Michael

**Comment by ChrisBr** [comment]
@hennevogel not too familiar with the dashboards but is something you want / can change?
