### ISSUE TITLE
Does it send points asynchronously?

### ISSUE THREAD

**Issue by sudhirj** [InfluxCommunity/influxdb-rails#2]
For the normal instrumentation, there's really no reason to hold up the entire app on each request while the gem makes three sync requests to influxdb. 

https://github.com/influxdb/influxdb-rails/blob/master/lib/influxdb-rails.rb#L67

Can we make these requests async? Or are they already configured to be async somewhere else?

**Comment by toddboom** [comment]
@sudhirj The underlying ruby gem supports async requests - I just need to make this configurable. I think async should probably be the default. I'll try to get that updated and pushed out in the next day or two. Thanks!

**Comment by toddboom** [comment]
@sudhirj The latest version of this gem will use async writes by default. Give it a try and let us know if you have any issues. Thanks!
