### ISSUE TITLE
Identify repo owner and move to InfluxCommunity org

### ISSUE THREAD

**Issue by Anaisdg** [InfluxCommunity/influxdb-rails#204]
The v1 client libraries for InfluxDB were typically developed and maintained by community members. They have all now been succeeded by v2 client libraries developed and maintained by InfluxData in partnership with Bonitoo.

If there are still users of this v1 client library, and they or somebody else are willing to keep them updated with security fixes at a minimum, this code should be moved to https://github.com/InfluxCommunity and control of it given to the new maintainers. Otherwise let's archive it in favor of the v2 client library.

**Comment by ChrisBr** [comment]
> If there are still users of this v1 client library,

Yes there are. 

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/3799140/202108692-e8b16a90-5808-4aaf-9207-2c2e61aa31b5.png">


> control of it given to the new maintainers.

@hennevogel and I have put quite some significant work into this and influxdb-rails gem so it's a bit harsh to come in and request this gem gets transferred to new maintainers. That's an interesting take of influxdb on open source.

**Comment by hennevogel** [comment]
>  They have all now been succeeded by v2 client libraries

Not this one :)

**Comment by hennevogel** [comment]
@Anaisdg if you want us to move somewhere else, just say the word. I don't care about the organization this resides in...
