### ISSUE TITLE
Upgrade to influx 0.9

### ISSUE THREAD

**Issue by kbrock** [InfluxCommunity/influxdb-rails#23]
Hi,

There is a big bold "Doesn't work with 0.9"
Could you share what needs to be done?

I'll start putting together some tasks, but any pointers would be appreciated.
I'll convert into a check list and do my best to tackle them.

**Comment by kbrock** [comment]
@beckettsean sorry the issue is vague. I am having trouble finding docs on changes to the api other than the introduction of tags.

I'm new to influxdb, so not sure the implications of this.
However, I have introduced instrumentation to rails code in the past with statsd/graphite. So this seems straight forward, if I knew what I was looking for.

**Comment by beckettsean** [comment]
This page describes the changes from a non-code perspective: https://influxdb.com/docs/v0.9/concepts/08_vs_09.html. The biggest issue is that the write path no longer uses JSON, but the line protocol. There are lots of small syntax tweaks to the InfluxQL as well. 

I would advise looking at the other libraries for the PRs that updated them to 0.9, or perhaps asking the maintainers what was needed.

**Comment by kbrock** [comment]
thanks

**Comment by tmc** [comment]
@toddboom is this issue still valid?

**Comment by dmke** [comment]
Nope.

**Comment by kbrock** [comment]
Thanks all
