### ISSUE TITLE
Broken gem

### ISSUE THREAD

**Issue by klippx** [InfluxCommunity/influxdb-rails#25]
Hello, 

Which version of influxdb and influxdb-rails gem are you using? 

I was evaluating to use influxdb-rails in our project, and while trying to follow the README on this repo I got many background errors, I found some discrepancies with how it uses influxdb-ruby;

![screen shot 2016-01-11 at 16 25 59](https://cloud.githubusercontent.com/assets/2785359/12237927/93204c8e-b881-11e5-9dd8-f48b0ad50dbd.png)
influxdb-rails usage of write_point has no values or tags keyword, just a simple json

![screen shot 2016-01-11 at 16 24 13](https://cloud.githubusercontent.com/assets/2785359/12237928/9321e418-b881-11e5-9743-4153e5b48f9d.png)
influxdb-ruby 0.2.3 expects a stricter structure of `data` parameter when used by `write_point` (containing `:values` and optional `:tags`) so that wont work...

![screen shot 2016-01-11 at 16 23 52](https://cloud.githubusercontent.com/assets/2785359/12237926/931dd77e-b881-11e5-8213-5e293a38a5a9.png)
influxdb-ruby 0.1.9 seems to be ok with this syntax but has other http errors possible related to influxdb version >= 0.9

I guess I would have to downgrade the installed influxdb service in addition to downgrading influxdb-rails gem to even try this out?

**Comment by bmxpert1** [comment]
@klippx it looks like I totally missed that write_point method call in the instrumentation.rb when making a pull-request a few weeks back to upgrade the influxdb-ruby version. I just made a pull-request, #26. Thanks for reporting this.

**Comment by aegaas** [comment]
I just started evaluating this gem for a project as well, and while I'm not sure this is related, I'm getting the following errors in my logs, and of course no data on the influxdb side:

> Cannot write data: #<InfluxDB::Error: {"error":"unable to parse 'rails.controller ': invalid field format\nunable to parse 'rails.view ': invalid field format\nunable to parse 'rails.db ': invalid field format"}

Any help on a new compatible release would certainly be appreciated!

**Comment by klippx** [comment]
@aegaas I have seen this is well, as you can see it has a trailing space that messes it up.

Fix is to set specific values in 

``` ruby
╰─○ cat config/initializers/influxdb-rails.rb
InfluxDB::Rails.configure do |config|
  config.influxdb_database = "rails"
  config.influxdb_username = "root"
  config.influxdb_password = "root"
  config.influxdb_hosts    = ["localhost"]
  config.influxdb_port     = 8086
  config.influxdb_port     = 8086
  config.ignored_environments = %w{}

  config.series_name_for_controller_runtimes = "klear.controller"
  config.series_name_for_view_runtimes       = "klear.view"
  config.series_name_for_db_runtimes         = "klear.db"
end
```

**Comment by bmxpert1** [comment]
@aegaas @klippx just for the record, I think this is an issue with influxdb-ruby which the PR https://github.com/influxdata/influxdb-ruby/pull/121 would fix. Haven't seen anything lately on getting that merged in though...

**Comment by bmxpert1** [comment]
But on the other hand, having whitespace on the end of a measurement name would probably cause future confusion, so @klippx's advice to remove that makes more sense.

**Comment by aegaas** [comment]
This is very strange guys, I have these series_name_for_*_runtimes values set like above, but I still get the error message like above, with the space. Perhaps there is something else at play here introducing the space?

**Comment by aegaas** [comment]
I forked the repo and used the gem straight from git. It seems to be working fine now! Time to publish a new gem :+1:
