### ISSUE TITLE
"error":"unable to parse 'rails.controller ': invalid field

### ISSUE THREAD

**Issue by ghost** [InfluxCommunity/influxdb-rails#27]
Hello, I'm getting the following error. I didn't change the initializer and server is running localhost:8083 with default authentication.

```
Cannot write data: #<InfluxDB::Error: {"error":"unable to parse 'rails.controller ': invalid field format\nunable to parse 'rails.view ': invalid field format\nunable to parse 'rails.db ': invalid field format"}
```

```
influx --version
InfluxDB shell 0.10.1
```

Any Idea ?

**Comment by bmxpert1** [comment]
@zenati I'm pretty sure this came up recently in #25 as well. The rubygems version of the repo has not been updated in a long while - https://rubygems.org/gems/influxdb-rails/versions/0.1.10. Try pointing to the github version directly in your rails project:

``` ruby
gem 'influxdb-rails', github: 'influxdata/influxdb-rails'
```

The better solution obviously being to publish a new version - but I'm not one of the admins :\ Although master is currently in a slight state of flux, mostly as it pertains to #26, so it's probably not quite ready for the new minor version.

**Comment by ghost** [comment]
@bmxpert1 Thanks, it works but there is still this error:

```
[InfluxDB] Failed to contact host localhost: #<Zlib::GzipFile::Error: not in gzip format>
```

Any Idea?

**Comment by bmxpert1** [comment]
@zenati I personally have not run into this, but I found this issue on the [influxdb-ruby](https://github.com/influxdata/influxdb-ruby) project which looks very similar: https://github.com/influxdata/influxdb-ruby/issues/116

**Comment by mbajur** [comment]
Guys,
i've tried installing influxdb-rails from git master but it still gives me the same error as in issue (well, almost)

```
InfluxDB::Rails.client.write_point("events", {url: "/foo", user_id: 1})
# Cannot write data: #<InfluxDB::Error: {"error":"unable to parse 'events ': invalid field format"}
```

any ideas / hot fixes?

ruby 2.2.1
rails 4.2.0
influxdb-rails 10016d0b0fa2c1fefcf14e18347ef3dcd55782a4

Thanks!

**Comment by ranchodeluxe** [comment]
same issue here. the default series in `config/initializers/influxdb-rails.rb` seem to be working fine:

``` bash
  config.series_name_for_controller_runtimes = "rails.controller"
  config.series_name_for_view_runtimes       = "rails.view"
  config.series_name_for_db_runtimes         = "rails.db"
```

But new subscriptions to `Notifications` throws a version of `"unable to parse '<series_name> '"`:

``` ruby
ActiveSupport::Notifications.subscribe("sql.active_record") do |name, start, finish, id, payload|
  InfluxDB::Rails.client.write_point(name,{value: (finish-start), start: start, finish: finish, name: name})
end
```

ruby 2.2.1
rails 3.2.22.1
influxdb-rails 10016d0

**Comment by ranchodeluxe** [comment]
@bmxpert1 @zenati and @mbajur 

I think I was able to pinpoint the problem if you're using `influxdb-rails (0.1.10)` with `influxdb-rails` github version 10016d0, but it'd be nice to get some eyes on it. Some of these issues are also mentioned in #25

The extra space on the series name that the error mentions seems to be coming from [this line of code](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/point_value.rb#L16) when there are no tags passed into `write_point`

Since there are no tags being passed, it made me realize that the expected `write_point` params weren't correct. I'm able to write events now with this nested `data` hash:

``` ruby
ActiveSupport::Notifications.subscribe("sql.active_record") do |name, start, finish, id, payload|
  InfluxDB::Rails.client.write_point(name ,{values: { time_delta: (finish-start) }, tags: { start: start, finish: finish } })
end
```
