### ISSUE TITLE
Issue a release for v0.2.0

### ISSUE THREAD

**Issue by robwdux** [InfluxCommunity/influxdb-rails#28]
From the Readme: "This library is now updated to require influxdb-ruby v0.2.0 and greater, meaning that only InfluxDB v0.9.x and higher will be supported."

Current release is v0.1.10

**Comment by robwdux** [comment]
I realize that you can install from the git repo, just don't understand why a gem wasn't cut when support was added for v0.9.x

**Comment by tmc** [comment]
@toddboom Hey todd could you cut a new release?

**Comment by agx** [comment]
influxdb-ruby is on 0.3.x already and it's incompatible with influxdb-rails since several months now. Can we have a 0.1.11 release please?

**Comment by dmke** [comment]
I will have a look at this on the weekend, I haven't yet had the time to familiarize myself with this codebase.

**Comment by agx** [comment]
On Tue, Nov 15, 2016 at 02:12:50PM -0800, Dominik Menke wrote:

> I will have a look at this on the weekend, I haven't yet had the time to familiarize myself with this codebase.

Great. Since the current version 0.1.10 on rubygems is not functional due to
the changed syntax of write_point just having current git as 0.1.11
would already by a huge improvement.

**Comment by agx** [comment]
@dmke Any news on this one?

**Comment by dmke** [comment]
Sorry, not really. I seem to not find a quiet moment lately...

Looking at #32 this should be easy enough, the failing test on MRI 1.9.3 + Rails 4.0 needs to be addressed though.

**Comment by agx** [comment]
@dmke updated #32 Tests are passing now. Can you spin a new gem?

**Comment by dmke** [comment]
I've merged PR #32 and am waiting for the specs to finish. Then I'll release a new gem version.

**Comment by dmke** [comment]
~~Test are passing, but I've got a permission error when pushing to rubygems.org (I've notified @toddboom about this).~~

~~For now, you can use this in your Gemfile until my permissions are sorted:~~

```ruby
gem "influxdb-rails", github: "influxdata/influxdb-rails", tag: "v0.1.11"
```

**Comment by dmke** [comment]
Well, v0.1.11 [has just landed](https://rubygems.org/gems/influxdb-rails).

**Comment by agx** [comment]
On Thu, Nov 24, 2016 at 02:10:20PM -0800, Dominik Menke wrote:
> Well, v0.1.11 [has just landed](https://rubygems.org/gems/influxdb-rails).

Awesome. Thanks a lot!
