### ISSUE TITLE
write urls as well?

### ISSUE THREAD

**Issue by tmc** [InfluxCommunity/influxdb-rails#30]
- Writing the urls that are being written would be interesting
- Writing current user would be interesting.

Perhaps this library should offer an easy way to control the write_point callsites?

**Comment by dmke** [comment]
Writing URLs turned out to be not a good idea. In sufficiently large Rails apps, you'll quickly exhaust tha tag limit on the server (see #54). Since we already write the controller and action name to InfluxDB, the actual URL does not provide much additional information.
