### ISSUE TITLE
ae3dc5756bfe43407f7992f689c2bc4ae6ff54c9 broke the tests

### ISSUE THREAD

**Issue by agx** [InfluxCommunity/influxdb-rails#33]
ae3dc5756bfe43407f7992f689c2bc4ae6ff54c9 set the default of retry to `true` but this isn't reflected in the tests.

**Comment by dmke** [comment]
Yikes. It must have been too late yesterday :-)

**Comment by dmke** [comment]
Ah, this wasn't ready for release anyway, as mentioned [here](https://github.com/influxdata/influxdb-rails/pull/18#issuecomment-262854757).
