### ISSUE TITLE
Logger set in config not respected

### ISSUE THREAD

**Issue by chrisarcand** [InfluxCommunity/influxdb-rails#35]
I'm setting up an initializer (from https://github.com/influxdata/influxdb-rails#usage) and no matter what I do, it seems I can't configure the logger as I expect:

```ruby
InfluxDB::Rails.configure do |config|
  # ...
  config.logger = false # Doesn't work (continues to log to STDOUT)
end

InfluxDB::Logging.logger = false # Doesn't work either (continues to log to STDOUT)
```

I still get incessant DEBUG logging sent to STDOUT, seemingly from here: https://github.com/influxdata/influxdb-ruby/blob/fa3c3f0b404aa87d8faa2272e556b884e3c961cd/lib/influxdb/logging.rb#L11-L14

Any tips here? I've also tried assigning to `::Rails.logger`, which correctly results in writing to the Rails log *but also* continues to write to STDOUT.

**Comment by dmke** [comment]
Hi, thanks for reporting this.

The issue seems to be a logic mismatch in what `InfluxDB::Logger` and `InfluxDB::Rails` interpret as "I don't want logging":

- `InfluxDB::Logger` is disabled [by setting `logger = false`](https://github.com/influxdata/influxdb-ruby/blob/fa3c3f0/lib/influxdb/logging.rb#L12)
- `InfluxDB::Rails` expects [setting `config.logger = nil`](https://github.com/influxdata/influxdb-rails/blob/ae3dc57/lib/influxdb-rails.rb#L30)

Additionally, the logger config is not passed down to `InfluxDB::Logger` from `InfluxDB::Rails`. To deactivate  the logging, I assume, you'll need something like this in your initializer:

```ruby
InfluxDB::Rails.configure do |config|
  # ...
  config.logger = nil
end
InfluxDB::Rails.client.logger = false
```

(I'm currently on mobile and cannot verify this)

**Comment by chrisarcand** [comment]
I should have included this previously...

I figured that sort of solution also, and sadly ran in to a `NoMethodError` when trying `InfluxDB::Rails.client.logger = false` as above. The reason is that [the writer is on the singleton class of the Logging module](https://github.com/influxdata/influxdb-ruby/blob/fa3c3f0b404aa87d8faa2272e556b884e3c961cd/lib/influxdb/logging.rb#L7-L9), not accessible on the client itself. This seems to be intended from the tests [here](https://github.com/influxdata/influxdb-ruby/blob/51c0704726901a3a31a159e3a23dd29a07023183/spec/influxdb/logging_spec.rb)

By the time configuration of the module is done in the initializer (editing `Logging`), `Logging` has already been included on `Client`, so has no effect (I suspect)

Sounds like some changes are needed to allow clients to have their own logger so as to be configurable in the way that you and I both expected it to be 😄

**Comment by dmke** [comment]
Indeed.

I'm going to take a closer look, and maybe refactor the `Logging` module.

**Comment by chrisarcand** [comment]
I debugged a bit and found that without any changing of configuration it defaults to using `ActiveSupport::Logger` [as is expected from the railtie.](https://github.com/influxdata/influxdb-rails/blob/e9e11a71e02698b45f0760a58194b0734a7398e0/lib/influxdb/rails/railtie.rb#L13). `InfluxDB::Logging.logger` (used by this gem) is the ActiveSupport logger, and it's what used to log the nonstop worker logging (`Checking background queue on thread 1 (3 active)`).

~~So maybe it's just something I'm not understanding with Logger/ActiveSupport::Logger? I'm not sure. I would expect it NOT to always print to STDOUT. I figured perhaps it was that I was in the development environment, so I tried running it with `RAILS_ENV=production` as well, but no difference.~~

Getting back to the main point of this issue, `config.logger = false` or `nil` doesn't deactivate the logger (on the `influxdb-ruby` side) and it probably should in some way.

**Comment by chrisarcand** [comment]
One more observation before I just nod my head and agree with you that the Logging module just needs to be refactored entirely: Theres some funny business with the instances that I mentioned above as when I run `RAILS_ENV=production`, even though the logger level (`Rails.logger.level`) is set to INFO (`1`), the DEBUG (`0`) messages continue to pour in to STDOUT. So it must be using a different logger.

**Comment by dmke** [comment]
Hm... the logger instantiating here is quite... convoluted. I need to setup a Rails app and manually step through the code to wrap my head around this issue :-)

I'm currently on a thight time budget though, so it may take a few days before can report on progress.

**Comment by chrisarcand** [comment]
No worries; I understand as I would have submitted some changes if I weren't in the same boat 😜 

For my purposes I've done a temporary hack and will circle back around when I can.

**Comment by dmke** [comment]
I belive this is now fixed. The next `influxdb-rails` release will depend on `influxdb` v0.4, which brings in a new log level knob, which can be setup independently from Rails' log:

```ruby
InfluxDB::Logging.log_level = Logger::INFO
```
