### ISSUE TITLE
does the aggregate method exist?

### ISSUE THREAD

**Issue by tobowers** [InfluxCommunity/influxdb-rails#4]
I don't see InfluxDB.aggregate defined:  https://github.com/influxdb/influxdb-rails/blob/master/lib/influxdb/rails/instrumentation.rb#L11

**Comment by toddboom** [comment]
@tobowers It doesn't really apply anymore. I believe that was just writing to a UDP collector that would roll up the data once a minute and write the result into a time series. InfluxDB would rather have you just write all that raw data in up front, and then you can perform aggregations on it later, or downsample with continuous queries.

**Comment by tobowers** [comment]
how does the code still work though?  Or is this another file that should be removed?  This one looked like it was actually being included to me.

**Comment by toddboom** [comment]
@tobowers I'll take a look. If it's still included, it shouldn't be.

**Comment by toddboom** [comment]
@tobowers yeah, that doesn't look right. i'll fix it.

**Comment by toddboom** [comment]
This was fixed by `bdb5bb79`.
