### ISSUE TITLE
rack middleware breaks streaming and dups the body?

### ISSUE THREAD

**Issue by tobowers** [InfluxCommunity/influxdb-rails#6]
Hey, what's the reason for this song and dance?

https://github.com/influxdb/influxdb-rails/blob/master/lib/influxdb/rails/rack.rb#L19-L21

I'm sure you have your reasons, it just looks like extra memory and work on requests

**Comment by toddboom** [comment]
@tobowers This may go way way back to something we were doing in the Errplane gem for Sinatra support. I'm guessing it's no longer needed. I shall yank it.

**Comment by toddboom** [comment]
@tobowers It looks like this was the reason:

http://johnbintz.github.io/blog/2012/03/05/closing-given-body-in-rack-middleware/

What say you?

**Comment by tobowers** [comment]
hmmm - I think rack is broken for modern streaming web, but it's what we got and what you have is good for now :)

**Comment by toddboom** [comment]
@tobowers Someday, maybe we'll live in the future. Closing this out for now - feel free to reopen if you end up finding a better solution!

**Comment by toddboom** [comment]
@tobowers Someone else brought this up in #9 and after doing some more digging, I decided to rip out the buffering code. I'm guessing/hoping that the deadlock issue was specific to an older version of Rack, and other middleware don't seem to have anything special to deal with the issue. Just released v0.1.6 with the fix.
