### ISSUE TITLE
1.0 Release?

### ISSUE THREAD

**Issue by hennevogel** [InfluxCommunity/influxdb-rails#69]
From #22 

> I'm going to include these changes in the upcoming 1.0 release (ETA: on the weekend).

"I love deadlines. I love the whooshing noise they make as they go by." ― Douglas Adams :wink: 

Do you still have any plans to relase 1.0 @dmke? Would be nice to get off @ChrisBr's custom copy gem for us. I also wait for this for https://github.com/hennevogel/influxdb-rails-dashboard somehow...

**Comment by dmke** [comment]
See https://github.com/influxdata/influxdb-rails/pull/66#issuecomment-506013919 (tl;dr: I'm looking for a new maintainer).

**Comment by ChrisBr** [comment]
I created this GH project to gather what needs to be done before we release 1.0:

https://github.com/influxdata/influxdb-rails/projects/1
