### ISSUE TITLE
Final release 0.4.99 release

### ISSUE THREAD

**Issue by ChrisBr** [InfluxCommunity/influxdb-rails#70]
We could also release a final 0.4.99 version introducing these deprecations, much like RSpec did transitioning from v2 to v3.

http://rspec.info/blog/2013/11/rspec-2-99-and-3-0-betas-have-been-released/

https://github.com/influxdata/influxdb-rails/pull/66 will introduce breaking changes, so we should think about the last beta release.

**Comment by hennevogel** [comment]
The deprecation message should link to something like https://github.com/influxdata/influxdb-rails/wiki/1.0-Changes

**Comment by hennevogel** [comment]
done...
