### ISSUE TITLE
Write upgrade guide

### ISSUE THREAD

**Issue by ChrisBr** [InfluxCommunity/influxdb-rails#71]
1.0 will introduce some breaking changes, we need to write an upgrade guide.

**Comment by hennevogel** [comment]
I'll get something going...

**Comment by hennevogel** [comment]
Working here

https://github.com/influxdata/influxdb-rails/wiki/1.0-Upgrade-Guide

**Comment by hennevogel** [comment]
@dmke you think we should mention anything else?

**Comment by dmke** [comment]
This looks great!

I'd keep a list of used hooks somewhere, so that users don't need to grep the source code to find out what can and cannot be disabled ("What can I stick into `ignored_hooks`?).

**Comment by ChrisBr** [comment]
> The following settings in your initializer don't have an effect anymore, you can remove them.

Is this true? I thought this will crash / break?

Also, in your table you mention `exceptions` in the 1.0 column but in the previous paragraph you say we dropped it, that sounds confusing 🤔 Do you mention it because we don't delete it or what is the reasoning? I would mention in the table that it is not used anymore. I would also mention that we support now an official dashboard (where you say `sorry but you need to update your dashboard` you could e.g. write `Sorry but you need to update your dashboard. To make this easier for you, we also support an official Grafana dashboard`).

WDYT?

**Comment by hennevogel** [comment]
> I'd keep a list of used hooks somewhere

They are already in README.md, I ~~should~~ have pointed to this!

**Comment by hennevogel** [comment]
> Is this true? I thought this will crash / break? 

True. -> #80

**Comment by hennevogel** [comment]
Added some things from the changelog, this is done.
