### ISSUE TITLE
Drop Exceptions

### ISSUE THREAD

**Issue by hennevogel** [InfluxCommunity/influxdb-rails#73]
While refactoring things for #56 I was trying for a brief time to unify subscriptions to `ActiveSupport` instrumentation and `HijackRenderException` and I started to wonder: Why do we do full blown exception tracking with this gem in a time series database? There are plenty of services, even FOSS ones, that do this ([errbit](https://github.com/errbit/errbit) || [sentry](https://sentry.io)) in a much nicer way.

I can understand that we maybe want to measure exceptions occurrence + some tags for it by default. But full blown?

What do you think?

**Comment by hennevogel** [comment]
I guess I'm talking to you @ChrisBr :smile:

**Comment by ChrisBr** [comment]
Yeah, this also confused me a little bit. No idea what the purpose of this feature was / is. So what do you wanna do? Drop the whole `HijackRenderException` tracking?

**Comment by hennevogel** [comment]
Either drop everything or I thought maybe injecting a custom `ActiveSupport` hook (something like `exception.influxdb_rails`) and a new `ExceptionSubscriber` that measures some of the stuff from `ExceptionPresenter.dimensions` and `ExceptionPresenter.values` as values/tags.
