### ISSUE TITLE
"raw" SQL time vs. ruby times

### ISSUE THREAD

**Issue by hennevogel** [InfluxCommunity/influxdb-rails#74]
Something we could consider...

https://twitter.com/nateberkopec/status/1159858382637076481?s=19

**Comment by ChrisBr** [comment]
Would be an interesting project how to get the actual SQL time 🤔 I think `sql.active_record` just gives you the overall time. 

https://guides.rubyonrails.org/active_support_instrumentation.html#sql-active-record

**Comment by hennevogel** [comment]
Measuring instantiation is all we can do for now I guess.
