### ISSUE TITLE
InfluxDB::Rails::Configuration not backward compatible

### ISSUE THREAD

**Issue by hennevogel** [InfluxCommunity/influxdb-rails#87]
There are many changes to the configuration options in 565aeefd3110263ec24b9201ed7488b08dd0aee9 that we have not handled in the [upgrade guide](https://github.com/influxdata/influxdb-rails/wiki/1.0-Upgrade-Guide) and that will make everything crash.

**Comment by ChrisBr** [comment]
Can you maybe provide a stacktrace etc of what exactly is crashing 😄 Otherwise it is hard to fix 😉
