### ISSUE TITLE
influxdb-rails gem destroys Rails ActionController::Live functionality

### ISSUE THREAD

**Issue by PascalTurbo** [InfluxCommunity/influxdb-rails#9]
Hi There,

I've been searching for a while why my application deny rails live streaming functionality. After creating a test application (and opening an issue on rails (https://github.com/rails/rails/issues/14523) I found out that after installing the influxdb-rails gem, live-streaming stops working.

**Comment by toddboom** [comment]
@PascalTurbo yeah, i think it has to do with something we're doing in the rack middleware. we discussed it in issue #6, but i'll try to find a way to solve it without breaking the streaming.
